// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tasinmaz_project.DataAccess;

namespace tasinmaz_project.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Ilce", b =>
                {
                    b.Property<int>("ilce_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ilce_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ilce_ad")
                        .HasColumnType("text");

                    b.Property<int>("sehir_id")
                        .HasColumnType("integer");

                    b.HasKey("ilce_id");

                    b.HasIndex("sehir_id");

                    b.ToTable("ilce");
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Kullanici", b =>
                {
                    b.Property<int>("kullanici_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kullanici_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("kullanici_name")
                        .HasColumnType("text");

                    b.Property<byte[]>("password_hash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("password_salt")
                        .HasColumnType("bytea");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.HasKey("kullanici_id");

                    b.ToTable("kullanici");
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("log_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("durum")
                        .HasColumnType("boolean");

                    b.Property<string>("islem_tipi")
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.Property<string>("log_ip")
                        .HasColumnType("text");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("log_id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("log");
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Mahalle", b =>
                {
                    b.Property<int>("mahalle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mahalle_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ilce_id")
                        .HasColumnType("integer");

                    b.Property<string>("mahalle_ad")
                        .HasColumnType("text");

                    b.HasKey("mahalle_id");

                    b.HasIndex("ilce_id");

                    b.ToTable("mahalle");
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Sehir", b =>
                {
                    b.Property<int>("sehir_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sehir_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("sehir_ad")
                        .HasColumnType("text");

                    b.HasKey("sehir_id");

                    b.ToTable("sehir");
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Tasinmaz", b =>
                {
                    b.Property<int>("tasinmaz_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tasinmaz_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ada")
                        .HasColumnType("text");

                    b.Property<string>("adres")
                        .HasColumnType("text");

                    b.Property<string>("koordinat")
                        .HasColumnType("text");

                    b.Property<int>("mahalle_id")
                        .HasColumnType("integer");

                    b.Property<string>("nitelik")
                        .HasColumnType("text");

                    b.Property<string>("parsel")
                        .HasColumnType("text");

                    b.HasKey("tasinmaz_id");

                    b.HasIndex("mahalle_id");

                    b.ToTable("tasinmaz");
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Ilce", b =>
                {
                    b.HasOne("tasinmaz_project.Entities.Concrete.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("sehir_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Log", b =>
                {
                    b.HasOne("tasinmaz_project.Entities.Concrete.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Mahalle", b =>
                {
                    b.HasOne("tasinmaz_project.Entities.Concrete.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("ilce_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tasinmaz_project.Entities.Concrete.Tasinmaz", b =>
                {
                    b.HasOne("tasinmaz_project.Entities.Concrete.Mahalle", "Mahalle")
                        .WithMany()
                        .HasForeignKey("mahalle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
